import { prisma } from '@/lib/prisma'
import { Prisma } from '@prisma/client'
import { notFound } from 'next/navigation'
import { Header } from '../../components/Header'
import { BottomNav } from '../../components/BottomNav'
import { RumorDetailContent } from './RumorDetailContent'
import type { Metadata } from 'next'

interface PageProps {
  params: Promise<{ id: string }>
}

// Gerar meta tags dinamicas para cada rumor (Twitter/Open Graph)
export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { id } = await params

  const rumor = await prisma.rumor.findUnique({
    where: { id },
    select: {
      title: true,
      playerName: true,
      toTeam: true,
      description: true,
    },
  })

  if (!rumor) {
    return {
      title: 'Rumor não encontrado - Palpiteiros',
    }
  }

  const title = `${rumor.title} - Palpiteiros`
  const description = rumor.description || `${rumor.playerName} pode ir para ${rumor.toTeam}. Veja o que as fontes dizem!`
  const url = `https://palpiteiro-mvp.vercel.app/rumor/${id}`

  // OG image is auto-generated by opengraph-image.tsx in this folder
  return {
    title,
    description,
    openGraph: {
      title,
      description,
      url,
      siteName: 'Palpiteiros',
      locale: 'pt_BR',
      type: 'article',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
    },
  }
}

export default async function RumorDetailPage({ params }: PageProps) {
  const { id } = await params

  const rumor = await prisma.rumor.findUnique({
    where: { id },
    include: {
      predictions: true,
      newsItems: {
        include: { newsItem: true },
        orderBy: { createdAt: 'desc' },
        take: 10,
      },
    },
  })

  if (!rumor) {
    notFound()
  }

  // Buscar notícias relacionadas separadamente para ter mais controle
  const orConditions: Prisma.NewsItemWhereInput[] = [
    { content: { contains: rumor.playerName, mode: 'insensitive' as Prisma.QueryMode } },
    { content: { contains: rumor.toTeam, mode: 'insensitive' as Prisma.QueryMode } },
  ]

  if (rumor.fromTeam) {
    orConditions.push({ content: { contains: rumor.fromTeam, mode: 'insensitive' as Prisma.QueryMode } })
  }

  const relatedNews = await prisma.newsItem.findMany({
    where: { OR: orConditions },
    orderBy: { publishedAt: 'desc' },
    take: 15,
  })

  // Separar por tipo de fonte
  const twitterNews = relatedNews.filter(n => n.source === 'twitter')
  const youtubeNews = relatedNews.filter(n => n.source === 'youtube')
  const articleNews = relatedNews.filter(n => n.source === 'globo' || n.source === 'uol')

  // Calcular sentimento baseado nas predictions
  const positiveCount = rumor.predictions.filter(p => p.prediction).length
  const totalCount = rumor.predictions.length
  const sentimentPercent = totalCount > 0
    ? Math.round((positiveCount / totalCount) * 100)
    : 50

  // Preparar dados para o client component
  const rumorData = {
    id: rumor.id,
    playerName: rumor.playerName,
    playerImage: rumor.playerImage,
    fromTeam: rumor.fromTeam,
    toTeam: rumor.toTeam,
    title: rumor.title,
    description: rumor.description,
    category: rumor.category,
    sentiment: rumor.sentiment,
    sentimentPercent,
    status: rumor.status,
    closesAt: rumor.closesAt.toISOString(),
    totalReactions: totalCount,
  }

  const newsData = {
    twitter: twitterNews.map(n => ({
      id: n.id,
      source: n.source,
      sourceUrl: n.sourceUrl,
      authorName: n.authorName,
      authorHandle: n.authorHandle,
      authorAvatar: n.authorAvatar,
      content: n.content,
      summary: n.summary,
      imageUrl: n.imageUrl,
      publishedAt: n.publishedAt.toISOString(),
      likes: n.likes,
      retweets: n.retweets,
      views: n.views,
    })),
    youtube: youtubeNews.map(n => ({
      id: n.id,
      source: n.source,
      sourceUrl: n.sourceUrl,
      authorName: n.authorName,
      authorHandle: n.authorHandle,
      authorAvatar: n.authorAvatar,
      content: n.content,
      summary: n.summary,
      imageUrl: n.imageUrl,
      publishedAt: n.publishedAt.toISOString(),
      likes: n.likes,
      retweets: n.retweets,
      views: n.views,
    })),
    articles: articleNews.map(n => ({
      id: n.id,
      source: n.source,
      sourceUrl: n.sourceUrl,
      authorName: n.authorName,
      authorHandle: n.authorHandle,
      authorAvatar: n.authorAvatar,
      content: n.content,
      summary: n.summary,
      imageUrl: n.imageUrl,
      publishedAt: n.publishedAt.toISOString(),
      likes: n.likes,
      retweets: n.retweets,
      views: n.views,
    })),
  }

  const hasContent = twitterNews.length > 0 || youtubeNews.length > 0 || articleNews.length > 0

  return (
    <main style={{ backgroundColor: '#0f0f1a', minHeight: '100vh', paddingBottom: '80px' }}>
      <Header title="Rumor" showBack />

      <RumorDetailContent
        rumor={rumorData}
        news={newsData}
        hasContent={hasContent}
      />

      <BottomNav />
    </main>
  )
}
